[package]
name = "deno_faas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_core = "0.152.0"
deno_runtime = "0.78.0"
tokio = { version = "1.21.1", features = ["full"] }

